### ISSUE TITLE
Maintaining the lesson

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/library-git-DEPRECATED#11]
I am happy to volunteer to maintain this - anyone else keen?

**Comment by jezcope** [comment]
@weaverbel As mentioned on gitter, I'm happy to be a second maintainer :)

**Comment by weaverbel** [comment]
Thanks - I have pinged @tracykteal about getting admin acfcess to all the repos we worked on.

**Comment by weaverbel** [comment]
Am closing this now we have two miantainers.

**Comment by jezcope** [comment]
@weaverbel I don't think I have admin access yet — worth pinging @tracykteal again?

**Comment by drjwbaker** [comment]
Now that @weaverbel is super busy with her new awesome job, so we need to recruit a third maintainer for this lesson?
