### ISSUE TITLE
Review exercise

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/library-git-DEPRECATED#42]
I think it would be good to think about uses for Git - maybe for versioning Library Guides or exhibition copy or whatever. But practical uses. The existing review exercise is not that great because most people haven't grasped enough of the workflow to have ideas though most people can relate Commit to Save, for example.
We want people to come away with an understanding of why they would bother, which is why we need a compelling exercise.
Library guides might be good as , in some cases, good text has been chucked away by a Track Changes edit cycle, whereas with Git, any lost text could always be brought back.
Also the strength of Git is that nothing is ever lost. That you can stuff up and recover from that by reverting to an older version.

**Comment by ccronje** [comment]
Only concern with this is how popular/invasive springshare libguides are - librarians enjoy using these (e.g. easy to get up to speed, user friendly GUI). Some libraries may be quite invested too (e.g. we just upgraded to v2). Pinging @libcce - he was trying out something along this line.

**Comment by libcce** [comment]
True, we were investigating whether we could use GitHub to collaboratively create content for our research community (which would be ingested into our website CMS). We decided that we were more or less shoehorning GitHub into our workflows. Now we have a GitHub study group exploring its possible use in research workflows and our own library workflows (with the goal of training our entire group of roughly 20 subject/collection development librarians). Jekyll/GitHub Pages remain a compelling case where we can work with researchers on campus to help them set up their own websites. We have a GitHub for teams training program coming up where we are working with a grad student in statistics. BTW, I should say that we don't use libguides.
