### ISSUE TITLE
Instructor Notes

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-git-DEPRECATED#49]
This lesson has out of date Instructor Notes http://data-lessons.github.io/library-git/guide/. These are helpful for passing on tips to potential instructors. See http://data-lessons.github.io/library-data-intro/guide/ for an example of how this might be done.

**Comment by VickySteeves** [comment]
Is this a duplicate of #50 ? Perhaps this one should be closed since the conversation is on #50.
