### ISSUE TITLE
Handout

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-git-DEPRECATED#50]
This lesson might benefit from making a handout of reference materials.

To do this add detail of commands/terminology under the keypoints headers for each lesson: for example, https://github.com/data-lessons/library-data-intro/blob/gh-pages/_episodes/04-regular-expressions.md. This effectively then builds a handout at - for example http://data-lessons.github.io/library-data-intro/reference/ - which can be printed out in advance of the session (librarians love handouts!)

Make sure you make a note of this in your Instructor Notes https://github.com/data-lessons/library-git/issues/49

**Comment by drjwbaker** [comment]
We have a request for a workshop in Italy in September. The workshop will be lead in English with Italian helpers. To make this work they are asking for there to be a handout in English that can be translated into Italian.

Maintainers @jezcope @weaverbel: any chance this work can be done by mid August so they can get this done for September?

I suspect having stable and detailed handouts is a good model for extending out reach to librarians who don't work in English (translating everything is not something every workshop can handle).

**Comment by drjwbaker** [comment]
Further to the above, maintainers @jezcope @weaverbel: I'm running a LC workhop in Padua with @danmichaelo in 14-15 September. They asked if we can get the handouts for the lessons in place so they can translate them for the workshop (they want to translate the handouts only, not the lessons!). This is one of the lessons we'll use. Any chance you could take a look and confirm it is good to go this week? (w/c 31 July) If not, could you give me a timescale I can pass on please?

**Comment by VickySteeves** [comment]
I don't know if you need something specific for this lesson, but there are many git cheat sheets that could help serve your purpose:

- https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf
- http://www.cheat-sheets.org/saved-copy/git-cheat-sheet.pdf
- https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet
