### ISSUE TITLE
no git clone

### ISSUE THREAD

**Issue by evanwill** [data-lessons/library-git-DEPRECATED#58]
This lesson starts with `git init` and sets a remote and pushes to GitHub. It does not mention `git clone` at all.

I use git for my work everyday, `git init` is something I have done only a handful of times, but I `git clone`  most days. If our aim is to teach people how to share code and interact with GitHub, it makes sense to at least mention `clone`. 

Personally, when I teach git workshops I mention `git init` and provide the workflow outline similar to the SWC lesson, but skip over it to a more common everyday workflow: create a repository on GitHub (with a readme), clone the repository, make changes, push. These seems to lower the cognitive load about init and setting remotes, which is hard to understand in the abstract. Starting with a clone seems to be a much more realistic workflow for using GitHub since it is what you will encounter in everyday work, collaborating with others or switching between computers.

Thoughts on possible approaches: 

1. add a `git clone` section at the end of the current demo to show how you would work with the test repo going forward (and reinforce / review git pull / add / commit / push). 
2. use the first `git init` lesson to explain git and working locally, but instead of creating a blank repo on GitHub and adding a remote, start a new demo that creates a GitHub repo with readme and git clone.

**Comment by weaverbel** [comment]
Thanks @evanwill This makes sense but I think we actually need to go a bit deeper here and figure out what the git lesson is aiming to do for librarians. There is no point replicating lessons done elsewhere, e.g. Software Carpentry, Programming Historian, so I think we need a good discussion first of why librarians should bother learnoing git at all. I think cloning a repo and building a blog or some other form of publishing via GitHub Pages would be good as so mnay librarians want to share info but have no mechanism. I think we need to bring in other people - I will paste a link to the issue into the chatroom as we meant to have this discussion post-2017-sprint andit never happened.

**Comment by evanwill** [comment]
I am a librarian!

As to repeating content, this lesson is currently following the SWC set up, starting with `git init` and adding remotes. I am saying we should avoid that since it isn't a realistic workflow for the average pragmatic librarian user and isn't the easiest way to start. I don't think the Programming Historian lessons are great for our use case. 

I commented a lot about Why git back on #7 (and just realized I raised this idea with init v. clone there as well). I think I will add some more thoughts to that issue rather than getting more off topic on this more specific thread.

**Comment by weaverbel** [comment]
I hear you @evanwill but there are a lot of librarians who have never heard of git and coudn't see why it might be relevant to them. I don't think we have yet come up with a compelling case of why they should learn it. That is what I would like the conversation to be about rather than the detail of what goes in the lesson. Hope that makes sense.

**Comment by evanwill** [comment]
not sure, isn't that the discussion in #7, with content to be wrapped into [what is git](http://data-lessons.github.io/library-git/01-what-is-git/)? 
This issue is about specifics in episode ["getting started with git"](http://data-lessons.github.io/library-git/02-getting-started/).

Or are you saying other issues shouldn't be discussed until **why** is fully fleshed out (like we need to major reorganization before commenting on any specifics)?

**Comment by drjwbaker** [comment]
> If our aim is to teach people how to share code and interact with GitHub, it makes sense to at least mention clone.

@evanwill: this isn't the aim at the moment. The aim to give learners an overview of Git and GitHub workflows. I'm uncomfortable with LC focusing on teaching GitHub for two reasons: 1) it is a company 2) it is an evolving GUI that causes overhead issues with lesson maintenance. But as @weaverbel says, we need to loop back to a discussion of the point of the lesson. @danmichaelo teached in admirably in Padova recently, but our main feedback was that the work they did wasn't hooked around a library example/dataset/scenario (which the shell, refine, and SQL lessons we taught are explicitly). That is why we keep coming back to https://github.com/data-lessons/library-git/issues/7.

**Comment by evanwill** [comment]
understood, but note clone isn't teaching github, I would stick with teaching specifically git via command line, but the way git is normally used is to clone a remote repository so you can work with yourself across multiple computers or collaborate with others. the remote could be github or any other cloud provider, a self hosted repository service, or a bare repository on your own server / computer.

**Comment by richyvk** [comment]
I like the idea of starting by creating a repo on github and cloning it, over git init. Personally I think it's easier than adding remotes. But, that assumes you want your repo public, which you might not.

If you're looking for a compelling use case for git/github for libs I'd say using GH Pages to build a website - say for a project. GH Pages is a great way to get a site up and running quickly and for free. 

Plus it would be a reason to learn some github (maybe accepting PRs, configuring GH Pages etc) and some git (writing the site on your computer). It wouldn't have to be Jekyll, that might be too much. Just a simple one page site written manually in HTML.

**Comment by weaverbel** [comment]
There is the Jekyll Now thing to create a Jekyll blog -I have done that in
a workshop andpeople liked the fact that they had a platform right then and
there.

I think that could be a good exercise.

cheers
B

Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by richyvk** [comment]
@weaverbel It could. But to be honest I feel like it might be good to not use Jekyll. Because I think people get it into their heads that if you want to use GH Pages you have to use Jekyll, which is not true at all.

**Comment by weaverbel** [comment]
Good point @richyvk. Could we create something about GH Pages instead?



Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus
